import Image from 'next/image';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '../../components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Morgan Selbekk</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='container'>
        <div className='intro'>
          <Image src='/morgan.png' alt='/' width={70} height={70} />
          <div className='me'>
            <h1 className='h1 mb-0.5'>Morgan Selbekk</h1>
            <p className='paragraph'>Software Engineer</p>
          </div>
        </div>
        <div className='mt-16'>
          <h2 className='h2 mb-4'>About me</h2>
          <p className='paragraph mb-2'>
            I’m a Developer living in San Fransisco. I have 8 years experience
            working in Ecommerce & Blockchain across Design, Development &
            Project Management.
          </p>
          <p className='paragraph'>
            The last 4 years have been spent building and running agencies
            specialising in the design and development of Ecommerce platforms,
            Content Management systems, NFT projects & Token staking web
            applications for clients such as{' '}
            <a href='https://www.google.com'>Versace</a>, <a>Clarins</a>,{' '}
            <a>Alkimi</a> & <a>JennyCo</a>
          </p>
        </div>
        <div className='mt-16'>
          <h2 className='h2 mb-4'>Experience</h2>
          <ul className='paragraph mb-2'>
            <li>Alkimi - Head of Project Management & Web3 Integrations</li>
            <li>Alkimi - Frontend Developer</li>
            <li>Zmags - Director of Global Design Services</li>
            <li>Zmags - Solutions Engineer</li>
            <li>Currys - Web Designer & Developer</li>
          </ul>
        </div>
        <div className='mt-16'>
          <h2 className='h2 mb-4'>Skills</h2>
          <p className='paragraph mb-2'>
            HTML | CSS | JavaScript | React | Next.js | Tailwind | MongoDB |
            Express | Node.js | Mongoose | JSON | Figma | Photoshop | Shopify |
            Wordpress
          </p>
        </div>
        <div className='mt-16'>
          <h2 className='h2 mb-4'>Latest Projects</h2>
          <ul className='paragraph mb-2'>
            <li>SplashScreen - Ecommerce Store</li>
            <li>Alkimi Labs - Token Staking App</li>
            <li>JennyCo - NFT Miniting site</li>
          </ul>
        </div>
        <div className='mt-16'>
          <h2 className='h2 mb-4'>Connect</h2>
          <ul className='paragraph mb-2'>
            <li>CV</li>
            <li>Twitter</li>
            <li>Github</li>
            <li>Linkedin</li>
            <li>Email</li>
          </ul>
        </div>
        <div className='fixed'>
          <Navbar />
        </div>
      </main>
    </>
  );
}
