import Head from 'next/head';
import Navbar from '../../../components/Navbar';
import Image from 'next/image';
import Link from 'next/link';
import Button from '../../../components/Button';

const splashPage = () => {
  return (
    <>
      <Head>
        <title>Morgan Selbekk</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='container'>
        <div className='flex justify-between'>
        <h1>Splash Page</h1>
        <Button />
        </div>
        <div className='my-10 flex flex-col gap-44'>
          <div>
            <div className='flex w-full h-full bg-[#242429] flex-col items-center py-6'>
              <Image src='/splash-screen.png' width={500} height={500} alt='splash screen' />
            </div>
            <p className='my-10'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, animi perspiciatis, doloribus soluta repellat nesciunt provident modi voluptatum non cum maiores beatae quidem obcaecati illo itaque libero ipsa facilis error.Lore. Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, animi perspiciatis, doloribus soluta repellat nesciunt provident modi voluptatum non cum maiores beatae quidem obcaecati illo itaque libero ipsa facilis error.Loremm</p>
            <h2 className='my-10'>Tech Stack</h2>
            <ul>
              <li className='mb-2'>HTML & CSS</li>
              <li className='mb-2'>React</li>
              <li className='mb-2'>React Bootstrap UI library</li>
              <li className='mb-2'>Redux & Redux Toolkit</li>
              <li className='mb-2'>Authentication with JWT & HTTP-Only cookies</li>
              <li className='mb-2'>PayPal</li>
              <li className='mb-2'>Multer & Cloudinary</li>
              <li className='mb-2'>Node.js</li>
              <li className='mb-2'>Express.js</li>
              <li className='mb-2'>Mongoose</li>
              <li className='mb-2'>MongoDB</li>
            </ul>
          </div>
          

        </div>
        <div className='fixed'>
          <Navbar />
        </div>
      </main>
    </>
  )
}

export default splashPage